#pragma kernel CSMain
#pragma kernel CSCull

struct VertexData
{
    float3 position; // Физическая локальная позиция вершины ландшафта
    float3 normal; // Нормаль поверхности чанка
};

// Сюда C# скрипт выгружает вершины меша текущих видимых чанков грани
StructuredBuffer<VertexData> _PlanetVertices;

// Выходной буфер матриц для отрисовки
RWStructuredBuffer<float4x4> _TransformBuf;

// Буферы для Indirect-куллинга по LOD-уровням камеры
AppendStructuredBuffer<float4x4> _CullBufLOD0;
AppendStructuredBuffer<float4x4> _CullBufLOD1;
AppendStructuredBuffer<float4x4> _CullBufLOD2;

StructuredBuffer<float4> _PlanesBuf;

float3 _CameraPosition;
float _LOD1DistSqr;
float _LOD2DistSqr;

uint _TotalInstances;
float _BaseScaleXZ;
float _BaseScaleY;
float _Radius; 
float4x4 _LocalToWorldMatrix;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
  
    if (id.x >= _TotalInstances)
    {
        _TransformBuf[id.x] = float4x4(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
        return;
    }

 
    VertexData planetVertex = _PlanetVertices[id.x];
    float3 localPos = planetVertex.position;
    float3 localNormal = normalize(planetVertex.normal);


    float3 pos = mul(_LocalToWorldMatrix, float4(localPos, 1.0f)).xyz;
    float3 normal = normalize(mul((float3x3) _LocalToWorldMatrix, localNormal));

  
    float3 up = normal;
    float3 tangent = (abs(up.y) > 0.999f) ? float3(1.0f, 0.0f, 0.0f) : float3(0.0f, 1.0f, 0.0f);
    float3 binormal = normalize(cross(up, tangent));
    tangent = cross(binormal, up);

 
    float randScale = 0.8f + (frac(sin(id.x) * 43758.5453f) * 0.4f);
    float finalScaleXZ = _BaseScaleXZ * randScale;
    float finalScaleY = _BaseScaleY * randScale;

    
    float4x4 transform = float4x4(
        tangent.x * finalScaleXZ, up.x * finalScaleY, binormal.x * finalScaleXZ, pos.x,
        tangent.y * finalScaleXZ, up.y * finalScaleY, binormal.y * finalScaleXZ, pos.y,
        tangent.z * finalScaleXZ, up.z * finalScaleY, binormal.z * finalScaleXZ, pos.z,
        0.0f, 0.0f, 0.0f, 1.0f
    );

    _TransformBuf[id.x] = transform;
}

[numthreads(64, 1, 1)]
void CSCull(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _TotalInstances)
        return;

    float4x4 transformationMatrix = _TransformBuf[id.x];
    float3 center = float3(transformationMatrix[0][3], transformationMatrix[1][3], transformationMatrix[2][3]);
    
    // Если матрица пустая — отсекаем поток
    if (dot(center, center) == 0.0f)
        return;

    // Проверка попадания в пирамиду видимости камеры (Frustum Culling)
    for (int i = 0; i < 6; i++)
    {
        float4 plane = _PlanesBuf[i];
        if (dot(plane.xyz, center) + plane.w <= -_Radius)
            return;
    }

    float3 dirToCamera = center - _CameraPosition;
    float distSqr = dot(dirToCamera, dirToCamera);

    // Распределяем выжившие кусты по LOD-буферам отрисовки
    if (distSqr < _LOD1DistSqr)
        _CullBufLOD0.Append(transformationMatrix);
    else if (distSqr < _LOD2DistSqr)
        _CullBufLOD1.Append(transformationMatrix);
    else
        _CullBufLOD2.Append(transformationMatrix);
}
